import { precacheAndRoute, matchPrecache } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { CacheFirst, NetworkFirst } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';

// Precache all of the assets generated by your build process.
// Their URLs are injected into the manifest variable below.
// This variable must be present somewhere in your service worker file.
precacheAndRoute(self.__WB_MANIFEST);

// Cache images with a Cache First strategy
registerRoute(
    ({ request }) => request.destination === 'image',
    new CacheFirst({
        cacheName: 'images',
        plugins: [
            new ExpirationPlugin({
                maxEntries: 60,
                maxAgeSeconds: 30 * 24 * 60 * 60, // 30 Days
            }),
        ],
    }),
);

// Cache fonts with a Cache First strategy
registerRoute(
    ({ request }) => request.destination === 'font',
    new CacheFirst({
        cacheName: 'webfonts',
        plugins: [
            new CacheableResponsePlugin({
                statuses: [0, 200],
            }),
            new ExpirationPlugin({
                maxEntries: 20,
                maxAgeSeconds: 365 * 24 * 60 * 60, // 1 Year
            }),
        ],
    }),
);

// Handle navigation requests (SPA) with fallback to precached index.html
registerRoute(
    ({ request }) => request.mode === 'navigate',
    async ({ request }) => {
        try {
            // Try network first
            return await fetch(request);
        } catch (error) {
            // Offline fallback: serve precached index.html using native browser Cache API
            let cachedResponse = await caches.match('/index.html');
            if (!cachedResponse) {
                cachedResponse = await caches.match('index.html');
            }
            if (cachedResponse) {
                return cachedResponse;
            }
            throw error;
        }
    }
);

// --- IndexedDB Helper (Singleton Connection) ---
const DB_NAME = 'WaveFitDB';
const DB_VERSION = 3;
const STORE_NAME = 'graphqlCache';

let dbPromise = null;

function getDB() {
    if (!dbPromise) {
        dbPromise = new Promise((resolve, reject) => {
            const request = indexedDB.open(DB_NAME, DB_VERSION);
            request.onerror = (event) => reject(event.target.error);
            request.onsuccess = (event) => resolve(event.target.result);
            request.onupgradeneeded = (event) => {
                const db = event.target.result;
                if (!db.objectStoreNames.contains(STORE_NAME)) {
                    db.createObjectStore(STORE_NAME, { keyPath: 'cacheKey' });
                }
                if (!db.objectStoreNames.contains('pendingMutations')) {
                    const store = db.createObjectStore('pendingMutations', { keyPath: 'id' });
                    store.createIndex('operationName', 'operationName', { unique: false });
                    store.createIndex('status', 'status', { unique: false });
                }
                if (!db.objectStoreNames.contains('authUser')) {
                    db.createObjectStore('authUser', { keyPath: 'id' });
                }
                if (!db.objectStoreNames.contains('exercises')) {
                    db.createObjectStore('exercises', { keyPath: 'id' });
                }
                if (!db.objectStoreNames.contains('routines')) {
                    db.createObjectStore('routines', { keyPath: 'id' });
                }
                if (!db.objectStoreNames.contains('plans')) {
                    db.createObjectStore('plans', { keyPath: 'id' });
                }
                if (!db.objectStoreNames.contains('tracking')) {
                    db.createObjectStore('tracking', { keyPath: 'id' });
                }
            };
        });
    }
    return dbPromise;
}

async function putInCache(cacheKey, data) {
    const db = await getDB();
    return new Promise((resolve, reject) => {
        const transaction = db.transaction([STORE_NAME], 'readwrite');
        const store = transaction.objectStore(STORE_NAME);
        const record = {
            cacheKey,
            data,
            updatedAt: Date.now()
        };
        const request = store.put(record);
        request.onsuccess = () => resolve();
        request.onerror = (e) => reject(e.target.error);
    });
}

async function getFromCache(cacheKey) {
    const db = await getDB();
    return new Promise((resolve, reject) => {
        const transaction = db.transaction([STORE_NAME], 'readonly');
        const store = transaction.objectStore(STORE_NAME);
        const request = store.get(cacheKey);
        request.onsuccess = (event) => {
            const result = event.target.result;
            resolve(result ? result.data : null);
        };
        request.onerror = (e) => reject(e.target.error);
    });
}

const GRAPHQL_WHITELIST = [
    'GetExercises',
    'Me',
    // Add other read operations here as they get implemented
];

// Handle API/GraphQL requests using IndexedDB for POST support
registerRoute(
    ({ url, request }) => url.pathname.includes('/graphql') && request.method === 'POST',
    async ({ request }) => {
        try {
            const reqClone = request.clone();
            const body = await reqClone.json();

            if (!body.operationName || !GRAPHQL_WHITELIST.includes(body.operationName)) {
                return fetch(request);
            }

            const cacheKey = JSON.stringify({
                operationName: body.operationName,
                variables: body.variables || {}
            });

            try {
                const response = await fetch(request);
                const resClone = response.clone();
                const resBody = await resClone.json();

                if (resBody && !resBody.errors) {
                    await putInCache(cacheKey, resBody.data);
                }

                return response;
            } catch (networkError) {
                const cachedData = await getFromCache(cacheKey);
                if (cachedData) {
                    return new Response(JSON.stringify({ data: cachedData }), {
                        headers: { 'Content-Type': 'application/json' }
                    });
                }
                throw networkError;
            }
        } catch (error) {
            return fetch(request);
        }
    }
);

self.addEventListener('message', (event) => {
    if (event.data && event.data.type === 'SKIP_WAITING') {
        self.skipWaiting();
    }
});

self.addEventListener('sync', (event) => {
    if (event.tag === 'sync-mutations') {
        event.waitUntil(
            self.clients.matchAll().then(clients => {
                clients.forEach(client => {
                    client.postMessage({ type: 'PROCESS_SYNC_QUEUE' });
                });
            })
        );
    }
});
